### ISSUE TITLE
How to use field update mask when updating the intent

### ISSUE THREAD

**Issue by mindartyr** [dialogflow/dialogflow-python-client-v2#89]
There are no examples how to use this field and I am not sure if it is implemented.
Can you provide some examples please?
Also, when you do the `get intent` call, it doesn't return `training_phrases` field.

**Comment by AlexSissoko** [comment]
When you use `get intent`, make sure you set `intent_view='INTENT_VIEW_FULL'`

**Comment by mindartyr** [comment]
@AlexSissoko 
Thanks a lot!
I've checked the previous issues and going to try to use `FieldMask`
Do you by chance know how to add new training phrases without loading old ones? I already have around 1500 in there :)

**Comment by AlexSissoko** [comment]
As far as I can tell, they haven't implemented that sort of functionality yet. But, I haven't exactly tinkered with stuff very much, so it might be possible.

Also, just in case you didn't know, there's a 2000 training phrase limit for an intent, so don't expect to be able to add infinite phrases.
I found it from really useful post on the api.ai discussion forum that talked about agent limitations but it's since been deleted with all other api.ai shenanigans. 
Dialogflow should really try to work on making that sort of information somewhat more available.

**Comment by mindartyr** [comment]
Yep, thanks, already know that they have a limit - they also have a size limit for the incoming request.

Would be great to have a possibility to train your agent continuously via API, but for now I don't see that they have it.
